### ISSUE TITLE
Credit

### ISSUE THREAD

**Issue by AliRn76** [clarketm/mergedeep#17]
Hi Travis
I couldn't find your email anywhere so I put this here as an issue :)

I used part of this package in my framework, I hope it's ok with you:
https://github.com/AliRn76/panther/blob/f54584a98d4b17b4e0ce23c71cec50f89fa1285f/panther/routings.py#L128

**Comment by jbylund** [comment]
[Relevant from the license](https://github.com/clarketm/mergedeep/blob/master/LICENSE#LL3C1-L3C94)
