### ISSUE TITLE
Add py.typed file so types can be used for users of mergedeep

### ISSUE THREAD

**Issue by RazerM** [clarketm/mergedeep#2]
See https://www.python.org/dev/peps/pep-0561/#id18

Without this, mypy won't type check mergedeep in code that uses it as a dependency:

```
error: Skipping analyzing 'mergedeep': found module but no type hints or library stubs
```

**Comment by WasabiFan** [comment]
It looks like this file is in the root of the repo rather than in the `mergedeep` module folder. Has anyone confirmed that type discovery for this module works right now? Initial indications in my project seem to suggest _no_.

**Comment by sshishov** [comment]
For me mypy is complaining actually that this package is not typed

**Comment by MicaelJarniac** [comment]
Mypy is also telling me that this project is not typed. I do also believe the `py.typed` file is in the wrong place.

**Comment by sshishov** [comment]
@clarketm could we please check this? Or do you need any help here?

**Comment by TomerGodinger** [comment]
Indeed, the `py.typed` file needs to be inside the `mergedeep` folder.
It would be nice if it was moved.

Is this library still being maintained? I see the last commits were made three years ago.
